### ISSUE TITLE
Error when loading API lib

### ISSUE THREAD

**Issue by tomsail** [conda-forge/opentelemac-feedstock#17]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Here a simple traceback of what happens when try to `import _api`:

```python
from telapy.api.t2d import Telemac2d
from mpi4py import MPI
cas_file = "telemac2d.cas"
user_fortran = None
comm = MPI.COMM_WORLD
study = Telemac2d(cas_file, user_fortran=user_fortran, comm=comm, stdout=0, recompile=True)
```

returns: 
```
Traceback (most recent call last):
  File "/home/tomsail/miniconda3/envs/pypostel/opentelemac/scripts/python3/telapy/api/api_module.py", line 149, in __init__
    import _api
ImportError: /home/tomsail/miniconda3/envs/pypostel/opentelemac/builds/gnu.dynamic/wrap_api/lib/../../lib/../../../../lib/libmpi_mpifh.so.40: undefined symbol: PMPI_Gather_init

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tomsail/miniconda3/envs/pypostel/opentelemac/scripts/python3/telapy/api/t2d.py", line 59, in __init__
    super(Telemac2d, self).__init__("t2d", casfile, user_fortran,
  File "/home/tomsail/miniconda3/envs/pypostel/opentelemac/scripts/python3/telapy/api/api_module.py", line 154, in __init__
    raise TelemacException(
utils.exceptions.TelemacException: /home/tomsail/miniconda3/envs/pypostel/opentelemac/builds/gnu.dynamic/wrap_api/lib/../../lib/../../../../lib/libmpi_mpifh.so.40: undefined symbol: PMPI_Gather_init
Error: unable to load the extension module _api.cpython-311-x86_64-linux-gnu.so
```

### Installed packages

# packages in environment at /home/tomsail/miniconda3/envs/pypostel:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aom                       3.9.1                hac33072_0    conda-forge
binutils                  2.43                 h4852527_1    conda-forge
binutils_impl_linux-64    2.43                 h4bf12b8_1    conda-forge
binutils_linux-64         2.43                 h4852527_1    conda-forge
blosc                     1.21.6               hef167b5_0    conda-forge
brotli                    1.1.0                hb9d3cd8_2    conda-forge
brotli-bin                1.1.0                hb9d3cd8_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.1               heb4867d_0    conda-forge
c-compiler                1.7.0                hd590300_1    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
compilers                 1.7.0                ha770c72_1    conda-forge
contourpy                 1.3.0           py311hd18a35c_2    conda-forge
cxx-compiler              1.7.0                h00ab1b0_1    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hd590300_0    conda-forge
eccodes                   2.38.0               hf413ef6_1    conda-forge
expat                     2.6.3                h5888daf_0    conda-forge
ffmpeg                    7.1.0           gpl_he2fd91e_701    conda-forge
fltk                      1.3.9                h9305793_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.54.1          py311h9ecbd09_0    conda-forge
fortran-compiler          1.7.0                heb67821_1    conda-forge
freeglut                  3.2.2                ha6d2627_3    conda-forge
freeimage                 3.18.0              h4bd6248_21    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freexl                    2.0.0                h743c826_0    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gcc                       12.4.0               h236703b_1    conda-forge
gcc_impl_linux-64         12.4.0               hb2e57f8_1    conda-forge
gcc_linux-64              12.4.0               h6b7512a_4    conda-forge
gdal                      3.9.2           py311h5159542_7    conda-forge
geos                      3.13.0               h5888daf_0    conda-forge
geotiff                   1.7.3                h77b800c_3    conda-forge
gfortran                  12.4.0               h236703b_1    conda-forge
gfortran_impl_linux-64    12.4.0               hc568b83_1    conda-forge
gfortran_linux-64         12.4.0               hd748a6a_4    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmsh                      4.12.2               h6b98cf8_0    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
gxx                       12.4.0               h236703b_1    conda-forge
gxx_impl_linux-64         12.4.0               h613a52c_1    conda-forge
gxx_linux-64              12.4.0               h8489865_4    conda-forge
harfbuzz                  9.0.0                hda332d3_1    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.4          nompi_h2d575fe_101    conda-forge
icu                       75.1                 he02047a_0    conda-forge
imath                     3.1.12               h7955e40_0    conda-forge
jasper                    4.2.4                h536e39c_0    conda-forge
jigsaw                    0.9.14               hcb278e6_1    conda-forge
json-c                    0.18                 h6688a6e_0    conda-forge
jxrlib                    1.1                  hd590300_3    conda-forge
kernel-headers_linux-64   3.10.0              he073ed8_17    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.7           py311hd18a35c_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_1    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240722.0      cxx17_h5888daf_1    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarchive                3.7.4                hfca40fe_0    conda-forge
libass                    0.17.3               h1dc1e6a_0    conda-forge
libblas                   3.9.0           24_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hb9d3cd8_2    conda-forge
libbrotlidec              1.1.0                hb9d3cd8_2    conda-forge
libbrotlienc              1.1.0                hb9d3cd8_2    conda-forge
libcblas                  3.9.0           24_linux64_openblas    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libdeflate                1.22                 hb9d3cd8_0    conda-forge
libdrm                    2.4.123              hb9d3cd8_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libegl                    1.7.0                ha4b6fd6_1    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-devel_linux-64     12.4.0             ha4f9413_101    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgdal-core              3.9.2                hd5b9bfb_7    conda-forge
libgfortran               14.1.0               h69a702a_1    conda-forge
libgfortran-ng            14.1.0               h69a702a_1    conda-forge
libgfortran5              14.1.0               hc5f4f2c_1    conda-forge
libgl                     1.7.0                ha4b6fd6_1    conda-forge
libglib                   2.82.1               h2ff4ddf_0    conda-forge
libglu                    9.0.0             ha6d2627_1004    conda-forge
libglvnd                  1.7.0                ha4b6fd6_1    conda-forge
libglx                    1.7.0                ha4b6fd6_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libhwloc                  2.11.1          default_hecaa2ac_1000    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
libkml                    1.3.0             hf539b9f_1021    conda-forge
liblapack                 3.9.0           24_linux64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_h2564987_115    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnl                     3.10.0               h4bc722e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libopenvino               2024.4.0             hac27bb2_1    conda-forge
libopenvino-auto-batch-plugin 2024.4.0             h4d9b6c2_1    conda-forge
libopenvino-auto-plugin   2024.4.0             h4d9b6c2_1    conda-forge
libopenvino-hetero-plugin 2024.4.0             h3f63f65_1    conda-forge
libopenvino-intel-cpu-plugin 2024.4.0             hac27bb2_1    conda-forge
libopenvino-intel-gpu-plugin 2024.4.0             hac27bb2_1    conda-forge
libopenvino-intel-npu-plugin 2024.4.0             hac27bb2_1    conda-forge
libopenvino-ir-frontend   2024.4.0             h3f63f65_1    conda-forge
libopenvino-onnx-frontend 2024.4.0             he882d9a_1    conda-forge
libopenvino-paddle-frontend 2024.4.0             he882d9a_1    conda-forge
libopenvino-pytorch-frontend 2024.4.0             h5888daf_1    conda-forge
libopenvino-tensorflow-frontend 2024.4.0             h9718a47_1    conda-forge
libopenvino-tensorflow-lite-frontend 2024.4.0             h5888daf_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpciaccess              0.18                 hd590300_0    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libprotobuf               5.27.5               h5b01275_2    conda-forge
libraw                    0.21.3               hca62329_0    conda-forge
librttopo                 1.1.0               h97f6797_17    conda-forge
libsanitizer              12.4.0               h46f95d5_1    conda-forge
libspatialite             5.1.0               h1b4f908_11    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-devel_linux-64  12.4.0             ha4f9413_101    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libtiff                   4.7.0                he137b08_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libva                     2.22.0               h8a09558_1    conda-forge
libvpx                    1.14.1               hac33072_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libzip                    1.11.1               hf83b1b0_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
matplotlib-base           3.9.2           py311h2b939e6_1    conda-forge
metis                     5.1.0             hd0bcaf9_1007    conda-forge
minizip                   4.0.7                h401b404_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    4.0.0           py311he576264_3    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
numpy                     1.26.4          py311h64a7726_0    conda-forge
occt                      7.7.2           novtk_h130ccc2_101    conda-forge
ocl-icd                   2.3.2                hd590300_1    conda-forge
openexr                   3.2.2                h04e0de5_2    conda-forge
openh264                  2.4.1                h59595ed_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openmpi                   5.0.5              h9a79eee_101    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
opentelemac               v8p5r0          py311hf5485a1_4    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pillow                    10.4.0          py311h4aec55e_1    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
proj                      9.5.0                h12925eb_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
pugixml                   1.14                 h59595ed_0    conda-forge
pyparsing                 3.1.4              pyhd8ed1ab_0    conda-forge
python                    3.11.10         hc5c86c4_2_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    5_cp311    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
rapidjson                 1.1.0.post20240409      hac33072_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.14.1          py311he1f765f_0    conda-forge
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
sqlite                    3.46.1               h9eae976_0    conda-forge
svt-av1                   2.2.1                h5888daf_0    conda-forge
sysroot_linux-64          2.17                h4a8ded7_17    conda-forge
tbb                       2021.13.0            h84d6215_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
uriparser                 0.9.8                hac33072_0    conda-forge
wayland                   1.23.1               h3e06ad9_0    conda-forge
wayland-protocols         1.37                 hd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h166bdaf_2    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xerces-c                  3.2.5                h988505b_2    conda-forge
xorg-libice               1.1.1                hb9d3cd8_1    conda-forge
xorg-libsm                1.2.4                he73a12e_1    conda-forge
xorg-libx11               1.8.10               h4f16b4b_0    conda-forge
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxfixes            6.0.1                hb9d3cd8_0    conda-forge
xorg-libxi                1.8.2                hb9d3cd8_0    conda-forge
xorg-libxmu               1.2.1                hb9d3cd8_1    conda-forge
xorg-libxrender           0.9.11               hb9d3cd8_1    conda-forge
xorg-libxt                1.3.0                hb9d3cd8_2    conda-forge
xorg-xextproto            7.3.0             hb9d3cd8_1004    conda-forge
xorg-xorgproto            2024.1               hb9d3cd8_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

### Environment info

conda info

     active environment : pypostel
    active env location : /home/tomsail/miniconda3/envs/pypostel
            shell level : 1
       user config file : /home/tomsail/.condarc
 populated config files : /home/tomsail/.condarc
          conda version : 24.1.2
    conda-build version : 24.9.0
         python version : 3.11.10.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.1.2=0
                          __glibc=2.35=0
                          __linux=6.8.0=0
                          __unix=0=0
       base environment : /home/tomsail/miniconda3  (writable)
      conda av data dir : /home/tomsail/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/tomsail/miniconda3/pkgs
                          /home/tomsail/.conda/pkgs
       envs directories : /home/tomsail/miniconda3/envs
                          /home/tomsail/.conda/envs
               platform : linux-64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.11.10 Linux/6.8.0-45-generic ubuntu/22.04.5 glibc/2.35 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.10
                UID:GID : 1000:1000
             netrc file : /home/tomsail/.netrc
           offline mode : False

**Comment by tomsail** [comment]
checked locally on python 3.11 & 3.12
fixed with #19, #15 and #16
